name: my_boat
description: "My Boat App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.2
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  flutter_redux: ^0.8.0
  redux: ^5.0.0
  pinput: ^4.0.0
  flutter_countdown_timer: ^4.1.0
  collection: ^1.18.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  dotted_line: ^3.2.2
  flutter_calendar_carousel: ^2.4.3
  dotted_border: ^2.1.0
  info_widget: ^1.0.0
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  win32: ^4.1.0
  video_player: ^2.5.5  

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0 #flutter pub run change_app_package_name:main
  flutter_native_splash: ^2.4.0 #dart run flutter_native_splash:create
  flutter_launcher_icons: ^0.13.1 #flutter pub pub run flutter_launcher_icons:main

flutter_icons:
  image_path_android: "assets/images/logo_image.png"
  image_path_ios: "assets/images/logo_image.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/sfui/

  fonts:
    - family: sfui
      fonts:
        - asset: assets/fonts/sfui/light.otf
          weight: 300
        - asset: assets/fonts/sfui/regular.ttf
          weight: 400
        - asset: assets/fonts/sfui/medium.otf
          weight: 500
        - asset: assets/fonts/sfui/semi-bold.otf
          weight: 600
        - asset: assets/fonts/sfui/bold.otf
          weight: 700
